### ISSUE TITLE
Scoring system

### ISSUE THREAD

**Issue by nellycheboi** [AugieSnackers/BinaryHero#11]
While the game ends when the player doesn't get all the balls on a particular level, I think we should acknowledge those who finish a level sooner than the allocated time. Consider use a time scoring system the less time the better the score. GameArena has three three variables gameArena(playerLevel, GameArenactivity, isBinary). Use the GameArenaActivity fro the .getContent() when wanting to have a pop dialog displaying scores. Should we facebook login?So that one can see how they rank-we spent years on it so we might as well use it. What do you think?Have fun

**Comment by scottdoberstein12** [comment]
We could do this two ways.  The first is to have a timer counting up and then when the level is finished, the timer stops and if its less than the last score it will be saved in a "level high score" variable and displayed at the end of the level in a popup or something.  We could alternatively do a CountDownTimer which sets a maximum time for the level, say 1 minute, and the high score is determined by which player had the most time left at the end.  This kills two birds with one stone if we want to have the level end if you dont finish in a certain amount of time.  This is kind of redundant if we already have the balls disappear after five rotations, so I'm looking into the first option.

**Comment by nellycheboi** [comment]
I like the first option. I saw earlier you were trying to add that chronometer to the frame layout. That won't work because the surface view will be drawn over  it. Trying the create a layout for the pop-up dialog and the add the time to it, Use the activity object to getContext()
